"""Owner_id on delete cascade

Revision ID: 3c9f8f5c093c
Revises: 9239da6e20a4
Create Date: 2023-07-22 10:00:56.730871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9f8f5c093c'
down_revision = '9239da6e20a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('owner_id', 'hotels', type_='foreignkey')
    op.create_foreign_key('owner_id', 'hotels', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('owner_id', 'hotels', type_='foreignkey')
    op.create_foreign_key('owner_id', 'hotels', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
