"""Bookings on delete cascade user_id

Revision ID: 2926e3c6ede0
Revises: 0c5c16f2e235
Create Date: 2023-07-25 18:10:47.458214

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2926e3c6ede0'
down_revision = '0c5c16f2e235'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookings_user_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key('bookings_user_id_fkey', 'bookings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
