"""image_path, rooms_quantity nullable False

Revision ID: 714676df80e3
Revises: 241c1f0a861f
Create Date: 2023-07-20 16:51:27.022562

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "714676df80e3"
down_revision = "241c1f0a861f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "hotels", "rooms_quantity", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("hotels", "image_path", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("hotels", "image_path", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "hotels", "rooms_quantity", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
