"""rooms_quantity nullable False

Revision ID: 9239da6e20a4
Revises: 714676df80e3
Create Date: 2023-07-20 17:39:47.828502

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9239da6e20a4"
down_revision = "714676df80e3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "hotels", "rooms_quantity", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "hotels", "rooms_quantity", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
