"""on delete rooms cascade

Revision ID: 864203b58c60
Revises: 3c9f8f5c093c
Create Date: 2023-07-23 15:46:08.594975

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '864203b58c60'
down_revision = '3c9f8f5c093c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rooms_hotel_id_fkey', 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key('rooms_hotel_id_fkey', 'rooms', 'hotels', ['hotel_id'], ['id'])
    # ### end Alembic commands ###
