"""fixed timezone info in created at field refresh session model

Revision ID: e08623a99b19
Revises: 848fd447c9a0
Create Date: 2023-08-10 18:42:21.277991

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e08623a99b19"
down_revision = "848fd447c9a0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refresh_sessions", "refresh_token", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "refresh_sessions", "expires_in", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "refresh_sessions", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "users",
        "role",
        existing_type=postgresql.ENUM("user", "hotel owner", "admin", name="role"),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=postgresql.ENUM("user", "hotel owner", "admin", name="role"),
        nullable=True,
    )
    op.alter_column(
        "refresh_sessions", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "refresh_sessions", "expires_in", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "refresh_sessions", "refresh_token", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###
