"""add owner_id to Hotel model

Revision ID: db82d4e39868
Revises: b1fd505c171a
Create Date: 2023-07-20 15:46:16.240822

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "db82d4e39868"
down_revision = "b1fd505c171a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hotels", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.create_foreign_key("owner_id", "hotels", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("owner_id", "hotels", type_="foreignkey")
    op.drop_column("hotels", "owner_id")
    # ### end Alembic commands ###
